export type OpcodeInfo = {
  name: string;
  desc: string;
  addressing: string;
  documented: boolean;
};

export const OPCODES: Record<number, OpcodeInfo> = {
  0x00: {
    name: "BRK",
    desc: "Break Command",
    addressing: "Implied",
    documented: true,
  },
  0x01: {
    name: "ORA",
    desc: '"OR" Memory with Accumulator',
    addressing: "X-Indexed Zero Page Indirect",
    documented: true,
  },
  0x02: {
    name: "KIL",
    desc: "Jam/Stop CPU",
    addressing: "Implied",
    documented: false,
  },
  0x03: {
    name: "SLO",
    desc: "Shift Left then OR with Accumulator",
    addressing: "X-Indexed Zero Page Indirect",
    documented: false,
  },
  0x04: {
    name: "NOP",
    desc: "No Operation",
    addressing: "Zero Page",
    documented: false,
  },
  0x05: {
    name: "ORA",
    desc: '"OR" Memory with Accumulator',
    addressing: "Zero Page",
    documented: true,
  },
  0x06: {
    name: "ASL",
    desc: "Arithmetic Shift Left",
    addressing: "Zero Page",
    documented: true,
  },
  0x07: {
    name: "SLO",
    desc: "Shift Left then OR with Accumulator",
    addressing: "Zero Page",
    documented: false,
  },
  0x08: {
    name: "PHP",
    desc: "Push Processor Status",
    addressing: "Implied",
    documented: true,
  },
  0x09: {
    name: "ORA",
    desc: '"OR" Memory with Accumulator',
    addressing: "Immediate",
    documented: true,
  },
  0x0a: {
    name: "ASL",
    desc: "Arithmetic Shift Left",
    addressing: "Accumulator",
    documented: true,
  },
  0x0b: {
    name: "ANC",
    desc: "AND Memory with Accumulator and Set Carry",
    addressing: "Immediate",
    documented: false,
  },
  0x0c: {
    name: "NOP",
    desc: "No Operation",
    addressing: "Absolute",
    documented: false,
  },
  0x0d: {
    name: "ORA",
    desc: '"OR" Memory with Accumulator',
    addressing: "Absolute",
    documented: true,
  },
  0x0e: {
    name: "ASL",
    desc: "Arithmetic Shift Left",
    addressing: "Absolute",
    documented: true,
  },
  0x0f: {
    name: "SLO",
    desc: "Shift Left then OR with Accumulator",
    addressing: "Absolute",
    documented: false,
  },
  0x10: {
    name: "BPL",
    desc: "Branch if Positive",
    addressing: "Relative",
    documented: true,
  },
  0x11: {
    name: "ORA",
    desc: '"OR" Memory with Accumulator',
    addressing: "Zero Page Indirect Indexed by Y",
    documented: true,
  },
  0x12: {
    name: "KIL",
    desc: "Jam/Stop CPU",
    addressing: "Implied",
    documented: false,
  },
  0x13: {
    name: "SLO",
    desc: "Shift Left then OR with Accumulator",
    addressing: "Zero Page Indirect Indexed by Y",
    documented: false,
  },
  0x14: {
    name: "NOP",
    desc: "No Operation",
    addressing: "Zero Page,X",
    documented: false,
  },
  0x15: {
    name: "ORA",
    desc: '"OR" Memory with Accumulator',
    addressing: "Zero Page,X",
    documented: true,
  },
  0x16: {
    name: "ASL",
    desc: "Arithmetic Shift Left",
    addressing: "Zero Page,X",
    documented: true,
  },
  0x17: {
    name: "SLO",
    desc: "Shift Left then OR with Accumulator",
    addressing: "Zero Page,X",
    documented: false,
  },
  0x18: {
    name: "CLC",
    desc: "Clear Carry Flag",
    addressing: "Implied",
    documented: true,
  },
  0x19: {
    name: "ORA",
    desc: '"OR" Memory with Accumulator',
    addressing: "Absolute,Y",
    documented: true,
  },
  0x1a: {
    name: "NOP",
    desc: "No Operation",
    addressing: "Implied",
    documented: false,
  },
  0x1b: {
    name: "SLO",
    desc: "Shift Left then OR with Accumulator",
    addressing: "Absolute,Y",
    documented: false,
  },
  0x1c: {
    name: "NOP",
    desc: "No Operation",
    addressing: "Absolute,X",
    documented: false,
  },
  0x1d: {
    name: "ORA",
    desc: '"OR" Memory with Accumulator',
    addressing: "Absolute,X",
    documented: true,
  },
  0x1e: {
    name: "ASL",
    desc: "Arithmetic Shift Left",
    addressing: "Absolute,X",
    documented: true,
  },
  0x1f: {
    name: "SLO",
    desc: "Shift Left then OR with Accumulator",
    addressing: "Absolute,X",
    documented: false,
  },
  0x20: {
    name: "JSR",
    desc: "Jump to Subroutine",
    addressing: "Absolute",
    documented: true,
  },
  0x21: {
    name: "AND",
    desc: '"AND" Memory with Accumulator',
    addressing: "X-Indexed Zero Page Indirect",
    documented: true,
  },
  0x22: {
    name: "KIL",
    desc: "Jam/Stop CPU",
    addressing: "Implied",
    documented: false,
  },
  0x23: {
    name: "RLA",
    desc: "Rotate Left and AND Accumulator",
    addressing: "X-Indexed Zero Page Indirect",
    documented: false,
  },
  0x24: {
    name: "BIT",
    desc: "Test Bits in Memory with Accumulator",
    addressing: "Zero Page",
    documented: true,
  },
  0x25: {
    name: "AND",
    desc: '"AND" Memory with Accumulator',
    addressing: "Zero Page",
    documented: true,
  },
  0x26: {
    name: "ROL",
    desc: "Rotate One Bit Left",
    addressing: "Zero Page",
    documented: true,
  },
  0x27: {
    name: "RLA",
    desc: "Rotate Left and AND Accumulator",
    addressing: "Zero Page",
    documented: false,
  },
  0x28: {
    name: "PLP",
    desc: "Pull Processor Status",
    addressing: "Implied",
    documented: true,
  },
  0x29: {
    name: "AND",
    desc: '"AND" Memory with Accumulator',
    addressing: "Immediate",
    documented: true,
  },
  0x2a: {
    name: "ROL",
    desc: "Rotate One Bit Left",
    addressing: "Accumulator",
    documented: true,
  },
  0x2b: {
    name: "ANC",
    desc: "AND Memory with Accumulator and Set Carry",
    addressing: "Immediate",
    documented: false,
  },
  0x2c: {
    name: "BIT",
    desc: "Test Bits in Memory with Accumulator",
    addressing: "Absolute",
    documented: true,
  },
  0x2d: {
    name: "AND",
    desc: '"AND" Memory with Accumulator',
    addressing: "Absolute",
    documented: true,
  },
  0x2e: {
    name: "ROL",
    desc: "Rotate One Bit Left",
    addressing: "Absolute",
    documented: true,
  },
  0x2f: {
    name: "RLA",
    desc: "Rotate Left and AND Accumulator",
    addressing: "Absolute",
    documented: false,
  },
  0x30: {
    name: "BMI",
    desc: "Branch if Minus",
    addressing: "Relative",
    documented: true,
  },
  0x31: {
    name: "AND",
    desc: '"AND" Memory with Accumulator',
    addressing: "Zero Page Indirect Indexed by Y",
    documented: true,
  },
  0x32: {
    name: "KIL",
    desc: "Jam/Stop CPU",
    addressing: "Implied",
    documented: false,
  },
  0x33: {
    name: "RLA",
    desc: "Rotate Left and AND Accumulator",
    addressing: "Zero Page Indirect Indexed by Y",
    documented: false,
  },
  0x34: {
    name: "NOP",
    desc: "No Operation",
    addressing: "Zero Page,X",
    documented: false,
  },
  0x35: {
    name: "AND",
    desc: '"AND" Memory with Accumulator',
    addressing: "Zero Page,X",
    documented: true,
  },
  0x36: {
    name: "ROL",
    desc: "Rotate One Bit Left",
    addressing: "Zero Page,X",
    documented: true,
  },
  0x37: {
    name: "RLA",
    desc: "Rotate Left and AND Accumulator",
    addressing: "Zero Page,X",
    documented: false,
  },
  0x38: {
    name: "SEC",
    desc: "Set Carry Flag",
    addressing: "Implied",
    documented: true,
  },
  0x39: {
    name: "AND",
    desc: '"AND" Memory with Accumulator',
    addressing: "Absolute,Y",
    documented: true,
  },
  0x3a: {
    name: "NOP",
    desc: "No Operation",
    addressing: "Implied",
    documented: false,
  },
  0x3b: {
    name: "RLA",
    desc: "Rotate Left and AND Accumulator",
    addressing: "Absolute,Y",
    documented: false,
  },
  0x3c: {
    name: "NOP",
    desc: "No Operation",
    addressing: "Absolute,X",
    documented: false,
  },
  0x3d: {
    name: "AND",
    desc: '"AND" Memory with Accumulator',
    addressing: "Absolute,X",
    documented: true,
  },
  0x3e: {
    name: "ROL",
    desc: "Rotate One Bit Left",
    addressing: "Absolute,X",
    documented: true,
  },
  0x3f: {
    name: "RLA",
    desc: "Rotate Left and AND Accumulator",
    addressing: "Absolute,X",
    documented: false,
  },
  0x40: {
    name: "RTI",
    desc: "Return from Interrupt",
    addressing: "Implied",
    documented: true,
  },
  0x41: {
    name: "EOR",
    desc: '"Exclusive OR" Memory with Accumulator',
    addressing: "X-Indexed Zero Page Indirect",
    documented: true,
  },
  0x42: {
    name: "KIL",
    desc: "Jam/Stop CPU",
    addressing: "Implied",
    documented: false,
  },
  0x43: {
    name: "SRE",
    desc: "Shift Right then Exclusive OR with Accumulator",
    addressing: "X-Indexed Zero Page Indirect",
    documented: false,
  },
  0x44: {
    name: "NOP",
    desc: "No Operation",
    addressing: "Zero Page",
    documented: false,
  },
  0x45: {
    name: "EOR",
    desc: '"Exclusive OR" Memory with Accumulator',
    addressing: "Zero Page",
    documented: true,
  },
  0x46: {
    name: "LSR",
    desc: "Logical Shift Right",
    addressing: "Zero Page",
    documented: true,
  },
  0x47: {
    name: "SRE",
    desc: "Shift Right then Exclusive OR with Accumulator",
    addressing: "Zero Page",
    documented: false,
  },
  0x48: {
    name: "PHA",
    desc: "Push Accumulator",
    addressing: "Implied",
    documented: true,
  },
  0x49: {
    name: "EOR",
    desc: '"Exclusive OR" Memory with Accumulator',
    addressing: "Immediate",
    documented: true,
  },
  0x4a: {
    name: "LSR",
    desc: "Logical Shift Right",
    addressing: "Accumulator",
    documented: true,
  },
  0x4b: {
    name: "ALR",
    desc: "AND Memory with Accumulator then Logical Shift Right",
    addressing: "Immediate",
    documented: false,
  },
  0x4c: {
    name: "JMP",
    desc: "Jump to Address",
    addressing: "Absolute",
    documented: true,
  },
  0x4d: {
    name: "EOR",
    desc: '"Exclusive OR" Memory with Accumulator',
    addressing: "Absolute",
    documented: true,
  },
  0x4e: {
    name: "LSR",
    desc: "Logical Shift Right",
    addressing: "Absolute",
    documented: true,
  },
  0x4f: {
    name: "SRE",
    desc: "Shift Right then Exclusive OR with Accumulator",
    addressing: "Absolute",
    documented: false,
  },
  0x50: {
    name: "BVC",
    desc: "Branch if Overflow Clear",
    addressing: "Relative",
    documented: true,
  },
  0x51: {
    name: "EOR",
    desc: '"Exclusive OR" Memory with Accumulator',
    addressing: "Zero Page Indirect Indexed by Y",
    documented: true,
  },
  0x52: {
    name: "KIL",
    desc: "Jam/Stop CPU",
    addressing: "Implied",
    documented: false,
  },
  0x53: {
    name: "SRE",
    desc: "Shift Right then Exclusive OR with Accumulator",
    addressing: "Zero Page Indirect Indexed by Y",
    documented: false,
  },
  0x54: {
    name: "NOP",
    desc: "No Operation",
    addressing: "Zero Page,X",
    documented: false,
  },
  0x55: {
    name: "EOR",
    desc: '"Exclusive OR" Memory with Accumulator',
    addressing: "Zero Page,X",
    documented: true,
  },
  0x56: {
    name: "LSR",
    desc: "Logical Shift Right",
    addressing: "Zero Page,X",
    documented: true,
  },
  0x57: {
    name: "SRE",
    desc: "Shift Right then Exclusive OR with Accumulator",
    addressing: "Zero Page,X",
    documented: false,
  },
  0x58: {
    name: "CLI",
    desc: "Clear Interrupt Disable",
    addressing: "Implied",
    documented: true,
  },
  0x59: {
    name: "EOR",
    desc: '"Exclusive OR" Memory with Accumulator',
    addressing: "Absolute,Y",
    documented: true,
  },
  0x5a: {
    name: "NOP",
    desc: "No Operation",
    addressing: "Implied",
    documented: false,
  },
  0x5b: {
    name: "SRE",
    desc: "Shift Right then Exclusive OR with Accumulator",
    addressing: "Absolute,Y",
    documented: false,
  },
  0x5c: {
    name: "NOP",
    desc: "No Operation",
    addressing: "Absolute,X",
    documented: false,
  },
  0x5d: {
    name: "EOR",
    desc: '"Exclusive OR" Memory with Accumulator',
    addressing: "Absolute,X",
    documented: true,
  },
  0x5e: {
    name: "LSR",
    desc: "Logical Shift Right",
    addressing: "Absolute,X",
    documented: true,
  },
  0x5f: {
    name: "SRE",
    desc: "Shift Right then Exclusive OR with Accumulator",
    addressing: "Absolute,X",
    documented: false,
  },
  0x60: {
    name: "RTS",
    desc: "Return from Subroutine",
    addressing: "Implied",
    documented: true,
  },
  0x61: {
    name: "ADC",
    desc: "Add Memory to Accumulator with Carry",
    addressing: "X-Indexed Zero Page Indirect",
    documented: true,
  },
  0x62: {
    name: "KIL",
    desc: "Jam/Stop CPU",
    addressing: "Implied",
    documented: false,
  },
  0x63: {
    name: "RRA",
    desc: "Rotate Right and Add with Carry",
    addressing: "X-Indexed Zero Page Indirect",
    documented: false,
  },
  0x64: {
    name: "NOP",
    desc: "No Operation",
    addressing: "Zero Page",
    documented: false,
  },
  0x65: {
    name: "ADC",
    desc: "Add Memory to Accumulator with Carry",
    addressing: "Zero Page",
    documented: true,
  },
  0x66: {
    name: "ROR",
    desc: "Rotate One Bit Right",
    addressing: "Zero Page",
    documented: true,
  },
  0x67: {
    name: "RRA",
    desc: "Rotate Right and Add with Carry",
    addressing: "Zero Page",
    documented: false,
  },
  0x68: {
    name: "PLA",
    desc: "Pull Accumulator",
    addressing: "Implied",
    documented: true,
  },
  0x69: {
    name: "ADC",
    desc: "Add Memory to Accumulator with Carry",
    addressing: "Immediate",
    documented: true,
  },
  0x6a: {
    name: "ROR",
    desc: "Rotate One Bit Right",
    addressing: "Accumulator",
    documented: true,
  },
  0x6b: {
    name: "ARR",
    desc: "AND Memory with Accumulator then Rotate Right",
    addressing: "Immediate",
    documented: false,
  },
  0x6c: {
    name: "JMP",
    desc: "Jump to Address",
    addressing: "Absolute Indirect",
    documented: true,
  },
  0x6d: {
    name: "ADC",
    desc: "Add Memory to Accumulator with Carry",
    addressing: "Absolute",
    documented: true,
  },
  0x6e: {
    name: "ROR",
    desc: "Rotate One Bit Right",
    addressing: "Absolute",
    documented: true,
  },
  0x6f: {
    name: "RRA",
    desc: "Rotate Right and Add with Carry",
    addressing: "Absolute",
    documented: false,
  },
  0x70: {
    name: "BVS",
    desc: "Branch if Overflow Set",
    addressing: "Relative",
    documented: true,
  },
  0x71: {
    name: "ADC",
    desc: "Add Memory to Accumulator with Carry",
    addressing: "Zero Page Indirect Indexed by Y",
    documented: true,
  },
  0x72: {
    name: "KIL",
    desc: "Jam/Stop CPU",
    addressing: "Implied",
    documented: false,
  },
  0x73: {
    name: "RRA",
    desc: "Rotate Right and Add with Carry",
    addressing: "Zero Page Indirect Indexed by Y",
    documented: false,
  },
  0x74: {
    name: "NOP",
    desc: "No Operation",
    addressing: "Zero Page,X",
    documented: false,
  },
  0x75: {
    name: "ADC",
    desc: "Add Memory to Accumulator with Carry",
    addressing: "Zero Page,X",
    documented: true,
  },
  0x76: {
    name: "ROR",
    desc: "Rotate One Bit Right",
    addressing: "Zero Page,X",
    documented: true,
  },
  0x77: {
    name: "RRA",
    desc: "Rotate Right and Add with Carry",
    addressing: "Zero Page,X",
    documented: false,
  },
  0x78: {
    name: "SEI",
    desc: "Set Interrupt Disable",
    addressing: "Implied",
    documented: true,
  },
  0x79: {
    name: "ADC",
    desc: "Add Memory to Accumulator with Carry",
    addressing: "Absolute,Y",
    documented: true,
  },
  0x7a: {
    name: "NOP",
    desc: "No Operation",
    addressing: "Implied",
    documented: false,
  },
  0x7b: {
    name: "RRA",
    desc: "Rotate Right and Add with Carry",
    addressing: "Absolute,Y",
    documented: false,
  },
  0x7c: {
    name: "NOP",
    desc: "No Operation",
    addressing: "Absolute,X",
    documented: false,
  },
  0x7d: {
    name: "ADC",
    desc: "Add Memory to Accumulator with Carry",
    addressing: "Absolute,X",
    documented: true,
  },
  0x7e: {
    name: "ROR",
    desc: "Rotate One Bit Right",
    addressing: "Absolute,X",
    documented: true,
  },
  0x7f: {
    name: "RRA",
    desc: "Rotate Right and Add with Carry",
    addressing: "Absolute,X",
    documented: false,
  },
  0x80: {
    name: "NOP",
    desc: "No Operation",
    addressing: "Immediate",
    documented: false,
  },
  0x81: {
    name: "STA",
    desc: "Store Accumulator in Memory",
    addressing: "X-Indexed Zero Page Indirect",
    documented: true,
  },
  0x82: {
    name: "NOP",
    desc: "No Operation",
    addressing: "Immediate",
    documented: false,
  },
  0x83: {
    name: "SAX",
    desc: "Store AND of Accumulator and Index Register X in Memory",
    addressing: "X-Indexed Zero Page Indirect",
    documented: false,
  },
  0x84: {
    name: "STY",
    desc: "Store Index Register Y in Memory",
    addressing: "Zero Page",
    documented: true,
  },
  0x85: {
    name: "STA",
    desc: "Store Accumulator in Memory",
    addressing: "Zero Page",
    documented: true,
  },
  0x86: {
    name: "STX",
    desc: "Store Index Register X in Memory",
    addressing: "Zero Page",
    documented: true,
  },
  0x87: {
    name: "SAX",
    desc: "Store AND of Accumulator and Index Register X in Memory",
    addressing: "Zero Page",
    documented: false,
  },
  0x88: {
    name: "DEY",
    desc: "Decrement Index Register Y",
    addressing: "Implied",
    documented: true,
  },
  0x89: {
    name: "NOP",
    desc: "No Operation",
    addressing: "Immediate",
    documented: false,
  },
  0x8a: {
    name: "TXA",
    desc: "Transfer Index Register X to Accumulator",
    addressing: "Implied",
    documented: true,
  },
  0x8b: {
    name: "XAA",
    desc: "Transfer X Register to Accumulator and AND with Immediate",
    addressing: "Immediate",
    documented: false,
  },
  0x8c: {
    name: "STY",
    desc: "Store Index Register Y in Memory",
    addressing: "Absolute",
    documented: true,
  },
  0x8d: {
    name: "STA",
    desc: "Store Accumulator in Memory",
    addressing: "Absolute",
    documented: true,
  },
  0x8e: {
    name: "STX",
    desc: "Store Index Register X in Memory",
    addressing: "Absolute",
    documented: true,
  },
  0x8f: {
    name: "SAX",
    desc: "Store AND of Accumulator and Index Register X in Memory",
    addressing: "Absolute",
    documented: false,
  },
  0x90: {
    name: "BCC",
    desc: "Branch if Carry Clear",
    addressing: "Relative",
    documented: true,
  },
  0x91: {
    name: "STA",
    desc: "Store Accumulator in Memory",
    addressing: "Zero Page Indirect Indexed by Y",
    documented: true,
  },
  0x92: {
    name: "KIL",
    desc: "Jam/Stop CPU",
    addressing: "Implied",
    documented: false,
  },
  0x93: {
    name: "AHX",
    desc: "Store AND of A and X and High Byte of Effective Address",
    addressing: "Zero Page Indirect Indexed by Y",
    documented: false,
  },
  0x94: {
    name: "STY",
    desc: "Store Index Register Y in Memory",
    addressing: "Zero Page,X",
    documented: true,
  },
  0x95: {
    name: "STA",
    desc: "Store Accumulator in Memory",
    addressing: "Zero Page,X",
    documented: true,
  },
  0x96: {
    name: "STX",
    desc: "Store Index Register X in Memory",
    addressing: "Zero Page,Y",
    documented: true,
  },
  0x97: {
    name: "SAX",
    desc: "Store AND of Accumulator and Index Register X in Memory",
    addressing: "Zero Page,Y",
    documented: false,
  },
  0x98: {
    name: "TYA",
    desc: "Transfer Index Register Y to Accumulator",
    addressing: "Implied",
    documented: true,
  },
  0x99: {
    name: "STA",
    desc: "Store Accumulator in Memory",
    addressing: "Absolute,Y",
    documented: true,
  },
  0x9a: {
    name: "TXS",
    desc: "Transfer Index Register X to Stack Pointer",
    addressing: "Implied",
    documented: true,
  },
  0x9b: {
    name: "TAS",
    desc: "Transfer A AND X to Stack Pointer",
    addressing: "Absolute,Y",
    documented: false,
  },
  0x9c: {
    name: "SHY",
    desc: "Store Index Register Y AND High Byte of Address + 1",
    addressing: "Absolute,X",
    documented: false,
  },
  0x9d: {
    name: "STA",
    desc: "Store Accumulator in Memory",
    addressing: "Absolute,X",
    documented: true,
  },
  0x9e: {
    name: "SHX",
    desc: "Store Index Register X AND High Byte of Address + 1",
    addressing: "Absolute,Y",
    documented: false,
  },
  0x9f: {
    name: "AHX",
    desc: "Store AND of A and X and High Byte of Effective Address",
    addressing: "Absolute,Y",
    documented: false,
  },
  0xa0: {
    name: "LDY",
    desc: "Load Index Register Y with Memory",
    addressing: "Immediate",
    documented: true,
  },
  0xa1: {
    name: "LDA",
    desc: "Load Accumulator with Memory",
    addressing: "X-Indexed Zero Page Indirect",
    documented: true,
  },
  0xa2: {
    name: "LDX",
    desc: "Load Index Register X with Memory",
    addressing: "Immediate",
    documented: true,
  },
  0xa3: {
    name: "LAX",
    desc: "Load Accumulator and Index Register X with Memory",
    addressing: "X-Indexed Zero Page Indirect",
    documented: false,
  },
  0xa4: {
    name: "LDY",
    desc: "Load Index Register Y with Memory",
    addressing: "Zero Page",
    documented: true,
  },
  0xa5: {
    name: "LDA",
    desc: "Load Accumulator with Memory",
    addressing: "Zero Page",
    documented: true,
  },
  0xa6: {
    name: "LDX",
    desc: "Load Index Register X with Memory",
    addressing: "Zero Page",
    documented: true,
  },
  0xa7: {
    name: "LAX",
    desc: "Load Accumulator and Index Register X with Memory",
    addressing: "Zero Page",
    documented: false,
  },
  0xa8: {
    name: "TAY",
    desc: "Transfer Accumulator to Index Register Y",
    addressing: "Implied",
    documented: true,
  },
  0xa9: {
    name: "LDA",
    desc: "Load Accumulator with Memory",
    addressing: "Immediate",
    documented: true,
  },
  0xaa: {
    name: "TAX",
    desc: "Transfer Accumulator to Index Register X",
    addressing: "Implied",
    documented: true,
  },
  0xab: {
    name: "LAX",
    desc: "Load Accumulator and Index Register X with Memory",
    addressing: "Immediate",
    documented: false,
  },
  0xac: {
    name: "LDY",
    desc: "Load Index Register Y with Memory",
    addressing: "Absolute",
    documented: true,
  },
  0xad: {
    name: "LDA",
    desc: "Load Accumulator with Memory",
    addressing: "Absolute",
    documented: true,
  },
  0xae: {
    name: "LDX",
    desc: "Load Index Register X with Memory",
    addressing: "Absolute",
    documented: true,
  },
  0xaf: {
    name: "LAX",
    desc: "Load Accumulator and Index Register X with Memory",
    addressing: "Absolute",
    documented: false,
  },
  0xb0: {
    name: "BCS",
    desc: "Branch if Carry Set",
    addressing: "Relative",
    documented: true,
  },
  0xb1: {
    name: "LDA",
    desc: "Load Accumulator with Memory",
    addressing: "Zero Page Indirect Indexed by Y",
    documented: true,
  },
  0xb2: {
    name: "KIL",
    desc: "Jam/Stop CPU",
    addressing: "Implied",
    documented: false,
  },
  0xb3: {
    name: "LAX",
    desc: "Load Accumulator and Index Register X with Memory",
    addressing: "Zero Page Indirect Indexed by Y",
    documented: false,
  },
  0xb4: {
    name: "LDY",
    desc: "Load Index Register Y with Memory",
    addressing: "Zero Page,X",
    documented: true,
  },
  0xb5: {
    name: "LDA",
    desc: "Load Accumulator with Memory",
    addressing: "Zero Page,X",
    documented: true,
  },
  0xb6: {
    name: "LDX",
    desc: "Load Index Register X with Memory",
    addressing: "Zero Page,Y",
    documented: true,
  },
  0xb7: {
    name: "LAX",
    desc: "Load Accumulator and Index Register X with Memory",
    addressing: "Zero Page,Y",
    documented: false,
  },
  0xb8: {
    name: "CLV",
    desc: "Clear Overflow Flag",
    addressing: "Implied",
    documented: true,
  },
  0xb9: {
    name: "LDA",
    desc: "Load Accumulator with Memory",
    addressing: "Absolute,Y",
    documented: true,
  },
  0xba: {
    name: "TSX",
    desc: "Transfer Stack Pointer to Index Register X",
    addressing: "Implied",
    documented: true,
  },
  0xbb: {
    name: "LAS",
    desc: "Load Accumulator and Stack Pointer with AND of Memory and Index X",
    addressing: "Absolute,Y",
    documented: false,
  },
  0xbc: {
    name: "LDY",
    desc: "Load Index Register Y with Memory",
    addressing: "Absolute,X",
    documented: true,
  },
  0xbd: {
    name: "LDA",
    desc: "Load Accumulator with Memory",
    addressing: "Absolute,X",
    documented: true,
  },
  0xbe: {
    name: "LDX",
    desc: "Load Index Register X with Memory",
    addressing: "Absolute,Y",
    documented: true,
  },
  0xbf: {
    name: "LAX",
    desc: "Load Accumulator and Index Register X with Memory",
    addressing: "Absolute,Y",
    documented: false,
  },
  0xc0: {
    name: "CPY",
    desc: "Compare Memory and Index Register Y",
    addressing: "Immediate",
    documented: true,
  },
  0xc1: {
    name: "CMP",
    desc: "Compare Memory and Accumulator",
    addressing: "X-Indexed Zero Page Indirect",
    documented: true,
  },
  0xc2: {
    name: "NOP",
    desc: "No Operation",
    addressing: "Immediate",
    documented: false,
  },
  0xc3: {
    name: "DCP",
    desc: "Decrement Memory and Compare with Accumulator",
    addressing: "X-Indexed Zero Page Indirect",
    documented: false,
  },
  0xc4: {
    name: "CPY",
    desc: "Compare Memory and Index Register Y",
    addressing: "Zero Page",
    documented: true,
  },
  0xc5: {
    name: "CMP",
    desc: "Compare Memory and Accumulator",
    addressing: "Zero Page",
    documented: true,
  },
  0xc6: {
    name: "DEC",
    desc: "Decrement Memory by One",
    addressing: "Zero Page",
    documented: true,
  },
  0xc7: {
    name: "DCP",
    desc: "Decrement Memory and Compare with Accumulator",
    addressing: "Zero Page",
    documented: false,
  },
  0xc8: {
    name: "INY",
    desc: "Increment Index Register Y by One",
    addressing: "Implied",
    documented: true,
  },
  0xc9: {
    name: "CMP",
    desc: "Compare Memory and Accumulator",
    addressing: "Immediate",
    documented: true,
  },
  0xca: {
    name: "DEX",
    desc: "Decrement Index Register X by One",
    addressing: "Implied",
    documented: true,
  },
  0xcb: {
    name: "AXS",
    desc: "AND Accumulator and Index X, Subtract Immediate",
    addressing: "Immediate",
    documented: false,
  },
  0xcc: {
    name: "CPY",
    desc: "Compare Memory and Index Register Y",
    addressing: "Absolute",
    documented: true,
  },
  0xcd: {
    name: "CMP",
    desc: "Compare Memory and Accumulator",
    addressing: "Absolute",
    documented: true,
  },
  0xce: {
    name: "DEC",
    desc: "Decrement Memory by One",
    addressing: "Absolute",
    documented: true,
  },
  0xcf: {
    name: "DCP",
    desc: "Decrement Memory and Compare with Accumulator",
    addressing: "Absolute",
    documented: false,
  },
  0xd0: {
    name: "BNE",
    desc: "Branch if Not Equal",
    addressing: "Relative",
    documented: true,
  },
  0xd1: {
    name: "CMP",
    desc: "Compare Memory and Accumulator",
    addressing: "Zero Page Indirect Indexed by Y",
    documented: true,
  },
  0xd2: {
    name: "KIL",
    desc: "Jam/Stop CPU",
    addressing: "Implied",
    documented: false,
  },
  0xd3: {
    name: "DCP",
    desc: "Decrement Memory and Compare with Accumulator",
    addressing: "Zero Page Indirect Indexed by Y",
    documented: false,
  },
  0xd4: {
    name: "NOP",
    desc: "No Operation",
    addressing: "Zero Page,X",
    documented: false,
  },
  0xd5: {
    name: "CMP",
    desc: "Compare Memory and Accumulator",
    addressing: "Zero Page,X",
    documented: true,
  },
  0xd6: {
    name: "DEC",
    desc: "Decrement Memory by One",
    addressing: "Zero Page,X",
    documented: true,
  },
  0xd7: {
    name: "DCP",
    desc: "Decrement Memory and Compare with Accumulator",
    addressing: "Zero Page,X",
    documented: false,
  },
  0xd8: {
    name: "CLD",
    desc: "Clear Decimal Mode",
    addressing: "Implied",
    documented: true,
  },
  0xd9: {
    name: "CMP",
    desc: "Compare Memory and Accumulator",
    addressing: "Absolute,Y",
    documented: true,
  },
  0xda: {
    name: "NOP",
    desc: "No Operation",
    addressing: "Implied",
    documented: false,
  },
  0xdb: {
    name: "DCP",
    desc: "Decrement Memory and Compare with Accumulator",
    addressing: "Absolute,Y",
    documented: false,
  },
  0xdc: {
    name: "NOP",
    desc: "No Operation",
    addressing: "Absolute,X",
    documented: false,
  },
  0xdd: {
    name: "CMP",
    desc: "Compare Memory and Accumulator",
    addressing: "Absolute,X",
    documented: true,
  },
  0xde: {
    name: "DEC",
    desc: "Decrement Memory by One",
    addressing: "Absolute,X",
    documented: true,
  },
  0xdf: {
    name: "DCP",
    desc: "Decrement Memory and Compare with Accumulator",
    addressing: "Absolute,X",
    documented: false,
  },
  0xe0: {
    name: "CPX",
    desc: "Compare Memory and Index Register X",
    addressing: "Immediate",
    documented: true,
  },
  0xe1: {
    name: "SBC",
    desc: "Subtract Memory from Accumulator with Borrow",
    addressing: "X-Indexed Zero Page Indirect",
    documented: true,
  },
  0xe2: {
    name: "NOP",
    desc: "No Operation",
    addressing: "Immediate",
    documented: false,
  },
  0xe3: {
    name: "ISC",
    desc: "Increment Memory, Subtract Memory from Accumulator",
    addressing: "X-Indexed Zero Page Indirect",
    documented: false,
  },
  0xe4: {
    name: "CPX",
    desc: "Compare Memory and Index Register X",
    addressing: "Zero Page",
    documented: true,
  },
  0xe5: {
    name: "SBC",
    desc: "Subtract Memory from Accumulator with Borrow",
    addressing: "Zero Page",
    documented: true,
  },
  0xe6: {
    name: "INC",
    desc: "Increment Memory by One",
    addressing: "Zero Page",
    documented: true,
  },
  0xe7: {
    name: "ISC",
    desc: "Increment Memory, Subtract Memory from Accumulator",
    addressing: "Zero Page",
    documented: false,
  },
  0xe8: {
    name: "INX",
    desc: "Increment Index Register X by One",
    addressing: "Implied",
    documented: true,
  },
  0xe9: {
    name: "SBC",
    desc: "Subtract Memory from Accumulator with Borrow",
    addressing: "Immediate",
    documented: true,
  },
  0xea: {
    name: "NOP",
    desc: "No Operation",
    addressing: "Implied",
    documented: true,
  },
  0xeb: {
    name: "SBC",
    desc: "Subtract Memory from Accumulator with Borrow",
    addressing: "Immediate",
    documented: false,
  },
  0xec: {
    name: "CPX",
    desc: "Compare Memory and Index Register X",
    addressing: "Absolute",
    documented: true,
  },
  0xed: {
    name: "SBC",
    desc: "Subtract Memory from Accumulator with Borrow",
    addressing: "Absolute",
    documented: true,
  },
  0xee: {
    name: "INC",
    desc: "Increment Memory by One",
    addressing: "Absolute",
    documented: true,
  },
  0xef: {
    name: "ISC",
    desc: "Increment Memory, Subtract Memory from Accumulator",
    addressing: "Absolute",
    documented: false,
  },
  0xf0: {
    name: "BEQ",
    desc: "Branch if Equal",
    addressing: "Relative",
    documented: true,
  },
  0xf1: {
    name: "SBC",
    desc: "Subtract Memory from Accumulator with Borrow",
    addressing: "Zero Page Indirect Indexed by Y",
    documented: true,
  },
  0xf2: {
    name: "KIL",
    desc: "Jam/Stop CPU",
    addressing: "Implied",
    documented: false,
  },
  0xf3: {
    name: "ISC",
    desc: "Increment Memory, Subtract Memory from Accumulator",
    addressing: "Zero Page Indirect Indexed by Y",
    documented: false,
  },
  0xf4: {
    name: "NOP",
    desc: "No Operation",
    addressing: "Zero Page,X",
    documented: false,
  },
  0xf5: {
    name: "SBC",
    desc: "Subtract Memory from Accumulator with Borrow",
    addressing: "Zero Page,X",
    documented: true,
  },
  0xf6: {
    name: "INC",
    desc: "Increment Memory by One",
    addressing: "Zero Page,X",
    documented: true,
  },
  0xf7: {
    name: "ISC",
    desc: "Increment Memory, Subtract Memory from Accumulator",
    addressing: "Zero Page,X",
    documented: false,
  },
  0xf8: {
    name: "SED",
    desc: "Set Decimal Mode",
    addressing: "Implied",
    documented: true,
  },
  0xf9: {
    name: "SBC",
    desc: "Subtract Memory from Accumulator with Borrow",
    addressing: "Absolute,Y",
    documented: true,
  },
  0xfa: {
    name: "NOP",
    desc: "No Operation",
    addressing: "Implied",
    documented: false,
  },
  0xfb: {
    name: "ISC",
    desc: "Increment Memory, Subtract Memory from Accumulator",
    addressing: "Absolute,Y",
    documented: false,
  },
  0xfc: {
    name: "NOP",
    desc: "No Operation",
    addressing: "Absolute,X",
    documented: false,
  },
  0xfd: {
    name: "SBC",
    desc: "Subtract Memory from Accumulator with Borrow",
    addressing: "Absolute,X",
    documented: true,
  },
  0xfe: {
    name: "INC",
    desc: "Increment Memory by One",
    addressing: "Absolute,X",
    documented: true,
  },
  0xff: {
    name: "ISC",
    desc: "Increment Memory, Subtract Memory from Accumulator",
    addressing: "Absolute,X",
    documented: false,
  },
};
